name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish_npm:
    if: "(github.repository == 'invertase/react-native-firebase') && (github.event_name == 'workflow_dispatch')"
    name: 'NPM'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Yarn Install
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn && yarn lerna:prepare
      - name: GIT Setup
        run: |
          git config --global user.name 'Invertase Publisher'
          git config --global user.email 'oss@invertase.io'
      - name: Publish Packages
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          git diff --exit-code
          yarn lerna changed
          yarn lerna version --yes --force-publish=*
          yarn lerna publish from-package --yes
        env:
          NPM_TOKEN: ${{ secrets.MIKEHARDY_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
